// data.js
// Este archivo contiene los datos de las frases.

const phrases = [
    { id: 1, text: "A todo trapo", meaning: "Cuando algo está muy bien hecho, con lujo y comodidad. 'Te fuiste a todo trapo' significa que lo pasaste increíble, a todo lujo." },
    { id: 2, text: "Le doy la pura salida al Rafita y saco el pan guardado", meaning: "Referencia a cómo su madre cuidaba 'para la foto' a su hijo médico (Rafita), pero apenas él se iba, ella volvía a disfrutar de la comida rica y la vida relajada." },
    { id: 3, text: "¡Qué cosa más grande!", meaning: "Expresión de asombro o sorpresa ante una situación inesperada." },
    { id: 4, text: "El fósforo", meaning: "Apodo o referencia cariñosa (comentario sobre Andrés)." },
    { id: 5, text: "Venía con la biblia debajo del brazo, y lo fui parando de entradita", meaning: "Frenar a alguien que viene con malas intenciones o sermones." },
    { id: 6, text: "Un soplamoco", meaning: "Un golpe rápido o coscorrón." },
    { id: 7, text: "Los voy a esperar con chilenitos", meaning: "Su forma clásica de decir que esperaba a las visitas con cariño y dulces ricos, algo que siempre hacía." },
    { id: 8, text: "Promedio", meaning: "Respuesta a '¿Cómo amaneció mamá?'. Ni bien ni mal, regular." },
    { id: 9, text: "El joooose", meaning: "Forma característica de llamar a José." },
    { id: 10, text: "Pata de laucha", meaning: "Alguien que está muy grave de salud o muriéndose." },
    { id: 11, text: "Arando de cabeza", meaning: "Cuando a alguien le va mal en lo que hace, que no le achunta a nada." },
    { id: 12, text: "Ni idea", meaning: "Desconocimiento total sobre algo." },
    { id: 13, text: "Cirole", meaning: "Expresión que usaba con un primo bueno para la fiesta. '¡Ya va Cirole!' le decía cuando iba a salir." },
    { id: 14, text: "Se me va a reventar la hiel", meaning: "Tener muchas ganas de comer algo rico que otro está comiendo o deseando." },
    { id: 15, text: "Anda tóxico", meaning: "Alguien que está de mal humor o negativo." },
    { id: 16, text: "No te pasí pa' la punta", meaning: "No te excedas, no abuses de la confianza." },
    { id: 17, text: "Paró la chala", meaning: "Falleció o dejó de funcionar algo." },
    { id: 18, text: "Busca tu alivio Toribio", meaning: "Rima para decir que cada uno busque su propia solución o descanso." },
    { id: 19, text: "Mírame de frente Vicente", meaning: "Pedir honestidad y franqueza." },
    { id: 20, text: "No mienta don Genaro", meaning: "Forma jocosa de acusar a alguien de mentir." },
    { id: 21, text: "Todo hermoso", meaning: "Expresión de optimismo o satisfacción." },
    { id: 22, text: "Acaloradita", meaning: "Alguien que es muy promiscua o que anda con un fuerte deseo sexual." },
    { id: 23, text: "Balsudo", meaning: "Alguien fresco o patudo." },
    { id: 24, text: "A cuchara para'", meaning: "Comer con muchas ganas o en gran cantidad." },
    { id: 25, text: "Le di con el mazazo", meaning: "Dar una noticia fuerte o poner fin a algo de golpe." },
    { id: 26, text: "Sopita de huesos, pura sustancia", meaning: "Comida reconfortante y nutritiva." },
    { id: 27, text: "Al tirante mi comandante", meaning: "Estar listo y dispuesto a obedecer o actuar." },
    { id: 28, text: "El cucurucho", meaning: "Referencia a algo en forma de cono o posiblemente un lugar." },
    { id: 29, text: "Jalisco", meaning: "Alguien insistente o porfiado (como en 'Jalisco nunca pierde')." },
    { id: 30, text: "Echar el pelo", meaning: "Burlarse o criticar a alguien." },
    { id: 31, text: "Esta es la vida del pobre obrero, mucho trabajo, poco dinero", meaning: "Refrán sobre la vida laboral dura." },
    { id: 32, text: "El cocaví", meaning: "La comida o merenda para el viaje o trabajo." },
    { id: 33, text: "Preparé un vituperio", meaning: "Cosas para picar o comer algo ligero." },
    { id: 34, text: "Carne de chancho", meaning: "Alguien resistente o que 'no se va nunca' (referente a visitas largas)." },
    { id: 35, text: "Está pasá' la naranja", meaning: "Algo que ya está pasado de maduro o alguien ...." },
    { id: 36, text: "Viejo prehistórico", meaning: "Alguien muy antiguo o con ideas pasadas de moda." },
    { id: 37, text: "Del año del ñauja", meaning: "Algo extremadamente viejo o antiguo." },
    { id: 38, text: "Mi hermana Estela tan buena", meaning: "Expresión de cariño y recuerdo hacia su hermana." },
    { id: 39, text: "Llega a péééte", meaning: "Expresión eufemística para denotar algo intenso o excesivo." },
    { id: 40, text: "Ahora se agranda la murienta", meaning: "Dicho sobre alguien que empieza a darse aires de grandeza o importancia." },
    { id: 41, text: "Don Genaro", meaning: "Referencia a un personaje (posiblemente de 'Los 80') o actitud de patrón." },
    { id: 42, text: "Miente no más huevooooon", meaning: "Acusación directa, jocosa y coloquial de que alguien está mintiendo." },
    { id: 43, text: "A tu parecer dime vo'", meaning: "Desafiar la opinión de otro o pedir explicaciones." },
    { id: 44, text: "Hola papi", meaning: "Saludo cariñoso característico." },
    { id: 45, text: "Pelucon", meaning: "Referencia a alguien con el pelo largo o desordenado." },
    { id: 46, text: "Tírate esa mantita guachito", meaning: "Petición cariñosa de abrigo o comodidad." },
    { id: 47, text: "Córtate esas pezuuuñas oye", meaning: "Mandato de higiene dicho con humor." },
    { id: 48, text: "Párate cocío", meaning: "Orden de levantarse, posiblemente a alguien que está durmiendo o ebrio." },
    { id: 49, text: "Tapa, tapa, tapa, que hace frío", meaning: "Insistencia en abrigarse bien." },
    { id: 50, text: "Mañana tempranito compramos", meaning: "Planificación de tareas domésticas o compras." },
    { id: 51, text: "El Jesús llega acá, se saca la polera y los zapatos y vamos fumando", meaning: "Descripción de una rutina relajada y familiar." },
    { id: 52, text: "Déjalo ahí no más, no me lo vay a botar", meaning: "Instrucción de cuidado con algún objeto." },
    { id: 53, text: "Estoy preparando unos ricos porotitos", meaning: "Anuncio de comida casera y reconfortante." },
    { id: 54, text: "Mañaaaaaaaaaaaana... ¡Altírooo!", meaning: "Sarcasmo sobre postergar algo indefinidamente o falta de credibilidad en la inmediatez." },
    { id: 55, text: "Fulminante", meaning: "Adjetivo para describir algo muy fuerte (contexto humorístico de olores)." },
    { id: 56, text: "Gatita panza arriba", meaning: "Estar muy relajada, cómoda o sumisa." },
    { id: 57, text: "Ese huevón si que es reondo", meaning: "Comentario sobre la forma física o quizás la torpeza de alguien." },
    { id: 58, text: "Manda y hazlo tú mismo", meaning: "Queja sobre tener que hacer algo uno mismo después de dar una orden." },
    { id: 59, text: "Salta pa' lla loco", meaning: "Rechazo tajante a una idea o persona molesta." },
    { id: 60, text: "Anda dando bote", meaning: "Estar desubicado, perdido o sobrando en un lugar." },
    { id: 61, text: "Con las puras patas y el buche", meaning: "Llegar a un lugar sin aportar nada, solo a comer o estar." },
    { id: 62, text: "Ya se le perdió... Ya no lo encontró", meaning: "Comentario resignado sobre alguien despistado." },
    { id: 63, text: "Soltero maduro, maricón seguro", meaning: "Dicho popular antiguo y pícaro." },
    { id: 64, text: "Las Gamelas", meaning: "Referencia específica a personas (probablemente gemelas)." },
    { id: 65, text: "Doña Pico", meaning: "Sobrenombre o personaje con humor pícaro." },
    { id: 66, text: "Vamos al pueblo a echar el pelo", meaning: "Salir a pasear, lucirse o vitrinear." },
    // Nuevas frases agregadas
    { id: 67, text: "Yo no quiero ir, contigo a bailar mi amor", meaning: "Negativa juguetona o cita de canción." },
    { id: 68, text: "A ese huevito le falta sal", meaning: "A alguien le falta 'chispa', gracia o inteligencia." },
    { id: 69, text: "El de arriba sabe más y averigua menos", meaning: "Confiando en el juicio divino o superior." },
    { id: 70, text: "Voy a ponerle una velita a la María", meaning: "Pedir un milagro o ayuda divina." },
    { id: 71, text: "Tripa de gato", meaning: "Algo muy delgado o quizás comida específica." },
    { id: 72, text: "Me quedo del one two", meaning: "Quedar sorprendido o helado." },
    { id: 73, text: "Héchale un corchito para que quede blanda", meaning: "Truco de cocina (para la carne)." },
    { id: 74, text: "El mote sin ceniza, no es mooooote", meaning: "Defensa de la preparación tradicional." },
    { id: 75, text: "Nunca María", meaning: "Negación rotunda al estilo personal." },
    { id: 76, text: "Súper, un 7", meaning: "Calificación máxima, todo excelente." },
    { id: 77, text: "La tengo corcuncha", meaning: "Tener la espalda torcida o adolorida." },
    { id: 78, text: "Las cañuelas", meaning: "Las piernas (especialmente si están flacas)." },
    { id: 79, text: "¿Y diay?", meaning: "¿Y entonces qué? / ¿Y de ahí?" },
    { id: 80, text: "Póngale perritos a la ropa", meaning: "Asegurar la ropa en el tendero." },
    { id: 81, text: "Bien estirada la ropa", meaning: "Instrucción precisa de lavado/tendido." },
    { id: 82, text: "Ese pollito", meaning: "Referencia tierna o burlona a alguien joven." },
    { id: 83, text: "¡Ay maricón!", meaning: "Grito de frustración, usualmente en fútbol." },
    { id: 84, text: "Le elevo los sopladores", meaning: "Le subo el ánimo o el ego a alguien." },
    { id: 85, text: "Pásele pa' trasito", meaning: "Invitación a pasar al fondo." },
    { id: 86, text: "Miti miti", meaning: "Mitad y mitad." },
    { id: 87, text: "Pantalones con guarda peo", meaning: "Pantalones de tiro alto." },
    { id: 88, text: "Vales un Perú", meaning: "Eres muy valioso." },
    { id: 89, text: "Eso lo hizo mami", meaning: "Reconocimiento a la labor de la mamá." },
    { id: 90, text: "La gaseosa", meaning: "La bebida." },
    { id: 91, text: "Este alimento les gustó, se echan pa' atrás comiendo", meaning: "Comiendo con mucho gusto." },
    { id: 92, text: "Se picó / Picotín", meaning: "Se enojó." },
    { id: 93, text: "Pechito panza arriba", meaning: "Descansando plácidamente." },
    { id: 94, text: "Ahí está la flaca que me regaló el Rafita", meaning: "Referencia a un cuadro o regalo específico." },
    { id: 95, text: "Este weón nació cansado", meaning: "Alguien flojo o sin energía." },
    { id: 96, text: "Ya se lo comió (hacer tira)", meaning: "Lo rompió o gastó." },
    { id: 97, text: "¿De adónde saliste tan fino?", meaning: "Burla ante alguien que finge refinamiento." },
    { id: 98, text: "Es lo que nos tocó no más", meaning: "Resignación ante la situación." },
    { id: 99, text: "Ta' helado el mote", meaning: "Hace frío o la situación está difícil." },
    { id: 100, text: "En un dos por tres", meaning: "Rápidamente." },
    { id: 101, text: "Piojo resucitado", meaning: "Alguien que mejoró su situación pero sigue siendo igual." },
    { id: 102, text: "Estás por webear estás", meaning: "Solo quieres molestar." },
    { id: 103, text: "El yayi", meaning: "Apodo." },
    { id: 104, text: "Ya foforiaron", meaning: "Ya se lucieron o hicieron alarde." },
    { id: 105, text: "Te volaste loco", meaning: "Te excediste." },
    { id: 106, text: "Nombres a Dios que salga todo bien", meaning: "Plegaria para que algo resulte." },
    { id: 107, text: "Aconcha que hace frío", meaning: "Protégete o acurrúcate." },
    { id: 108, text: "Raja Chumingo a la leña", meaning: "Mandato rápido para ir a buscar leña." },
    { id: 109, text: "El que guarda siempre tiene", meaning: "Refrán de ahorro." },
    { id: 110, text: "Hace falta la tonta", meaning: "Hace falta una copita o algo específico." },
    { id: 111, text: "Quedaron pochitos", meaning: "Quedaron llenos (de comida)." },
    { id: 112, text: "Anday como el peor de los cesantes", meaning: "Andar desaliñado o mal vestido." },
    { id: 113, text: "Cáchalasnunca", meaning: "Nunca entiendes o nunca lo logras." },
    { id: 114, text: "Potiches", meaning: "Adorno de poco valor o persona que está solo de adorno." },
    { id: 115, text: "Consejo de frascos", meaning: "Para abrir los frascos, levántale la tapa con un cuchillo porque están sellados al vacío." },
    { id: 116, text: "Una cosa u otra", meaning: "Indecisión o alternativa." },
    { id: 117, text: "Están mis tres hijos, llegó el José qué bonito", meaning: "Alegría por tener a la familia reunida." },
    { id: 118, text: "Me está haciendo clara de huevo", meaning: "Me está ignorando o haciendo esperar." },
    { id: 119, text: "Coronelito", meaning: "Apodo o referencia." },
    { id: 120, text: "Solo pirincho", meaning: "Algo simple o alguien solo." },
    { id: 121, text: "Te aletean los tebos", meaning: "Te tiemblan las piernas o estás nervioso." },
    { id: 122, text: "Te estoy sapiando", meaning: "Te estoy vigilando." },
    { id: 123, text: "Las puras wiulas", meaning: "Solo los restos o hilachas." },
    { id: 124, text: "Como te ven te tratan", meaning: "La importancia de la apariencia." },
    { id: 125, text: "Las puras garras", meaning: "Queda solo lo malo o lo feo." },
    { id: 126, text: "La siute", meaning: "Alguien que se cree de clase alta." },
    { id: 127, text: "Te agarro de las huilas", meaning: "Te tomo del pelo o ropa (amenaza juguetona)." },
    { id: 128, text: "Bájate Pacheco", meaning: "Bájate de la nube, no te creas tanto." },
    { id: 129, text: "Te vuelo los sopladores", meaning: "Te golpeo (amenaza)." },
    { id: 130, text: "Lo agarré del pihuelo", meaning: "Lo tomé de donde más le duele o dominé." },
    { id: 131, text: "Hay que invertir, no hay que ser miserable", meaning: "Consejo sobre gastos." },
    { id: 132, text: "El tomatodo", meaning: "Juguete o situación de beber todo." },
    { id: 133, text: "Zorra tirando", meaning: "Pasándola muy bien." },
    { id: 134, text: "Usted fue, general", meaning: "Usted mandó o decidió." },
    { id: 135, text: "Qué te vai a comparar conmigo, yo soy señora y vos revolcá'", meaning: "Poniendo límites de estatus con humor." },
    { id: 136, text: "Me emperifollo y voy", meaning: "Me arreglo bien y salgo." },
    { id: 137, text: "Vamos marchando / rumbiando", meaning: "Vámonos yendo." },
    { id: 138, text: "Échate una agüita", meaning: "Lávate un poco." },
    { id: 139, text: "La pilla", meaning: "La astuta." },
    { id: 140, text: "Los Oster", meaning: "Referencia a electrodomésticos o calidad." },
    { id: 141, text: "Los Antares de la Luz", meaning: "Referencia a secta o grupo raro." },
    { id: 142, text: "Ese huevón nació operado", meaning: "Es flojo desde nacimiento." },
    { id: 143, text: "Debe quedar bien cocido", meaning: "Instrucción de cocina importante." },
    { id: 144, text: "Puro billete", meaning: "Solo interés en el dinero." },
    { id: 145, text: "Vamos progresando", meaning: "Mejorando poco a poco." },
    { id: 146, text: "Mi terruño", meaning: "Mi tierra, mi hogar." },
    { id: 147, text: "La comida va andando", meaning: "Ya se está cocinando." },
    { id: 148, text: "¿Dónde andará mi tío?", meaning: "Pregunta retórica." },
    { id: 149, text: "Ya viene esta vieja mierda, dile que no estoy", meaning: "Humor negro sobre visitas indeseadas." },
    { id: 150, text: "Póngale llave al portón", meaning: "Seguridad ante todo." },
    { id: 151, text: "Rintintín / Nero", meaning: "Nombres de perros o apodos." },
    { id: 152, text: "Quedó mundial", meaning: "Quedó espectacular." },
    { id: 153, text: "Se peinan", meaning: "Son expertos en algo." },
    { id: 154, text: "Dígales que estoy durmiendo, que ando en San Carlos", meaning: "Excusas para no atender." },
    { id: 155, text: "Aprende el rubro", meaning: "Aprende cómo se hacen las cosas." },
    { id: 156, text: "El botín", meaning: "El tesoro o ganancia." },
    { id: 157, text: "Chao no más", meaning: "Despedida simple." },
    { id: 158, text: "Mi todo / Mi rey", meaning: "Expresiones de máximo cariño." },
    { id: 159, text: "El ñoño", meaning: "Apodo." },
    { id: 160, text: "¿Y tú, estay operado?", meaning: "¿Por qué no ayudas? (como si estuviera convaleciente)." },
    { id: 161, text: "La zorrita", meaning: "Apodo o referencia." },
    { id: 162, text: "Hijo de la zunca", meaning: "Insulto suave o referencia." },
    { id: 163, text: "Tú tenís de todo pu' cabrita", meaning: "Reconociendo que alguien está bien equipado." },
    { id: 164, text: "Andái con la coronta pelá'", meaning: "Andar sin dinero o sin nada." },
    { id: 165, text: "Se botó", meaning: "Se lució o fue generoso." },
    { id: 166, text: "Me quedo flor flay", meaning: "Quedo excelente, listo." },
    { id: 167, text: "El condoro", meaning: "El error o pastelazo." },
    { id: 168, text: "Chao Peters", meaning: "Despedida jocosa." },
    { id: 169, text: "Ohh Sugar Sugar", meaning: "Cantando la canción." },
    { id: 170, text: "Pasado pa' la cabina / Pa'l volante", meaning: "Olor fuerte a axila." },
    { id: 171, text: "Acabo de mundo", meaning: "Desastre total o fin de los tiempos." },
    { id: 172, text: "Mundial", meaning: "Excelente, de nivel mundial." },
    { id: 173, text: "Callampín bombín", meaning: "No le importa nada o es irrelevante." },
    { id: 174, text: "Como el buey Perú", meaning: "Perdido o lejos." },
    { id: 175, text: "Tío Baucha", meaning: "Personaje." },
    { id: 176, text: "Asopado", meaning: "Tonto o lento." },
    { id: 177, text: "Andái Pickle", meaning: "Estás enojado (picado)." },
    { id: 178, text: "Cero nervios", meaning: "Tranquilo." },
    { id: 179, text: "La jeta le llega al suelo", meaning: "Tiene la cara larga (tristeza o enojo)." },
    { id: 180, text: "Guata lápiz", meaning: "Muy flaco (la guata pegada a la espalda)." },
    { id: 181, text: "Cariñoso de la olla", meaning: "Le gusta comer." },
    { id: 182, text: "Tragallón", meaning: "Comilón." },
    { id: 183, text: "Sopas tontas", meaning: "Cosas sin importancia." },
    { id: 184, text: "El tufaso / El sopita", meaning: "Mal aliento / Apodo." },
    { id: 185, text: "Teta monja", meaning: "Pechos grandes." },
    { id: 186, text: "Te corre el very", meaning: "Te corre el viento (o alguna referencia sexual)." },
    { id: 187, text: "Los epilépticos / Los zorriáticos", meaning: "Ataques de nervios o locura." },
    { id: 188, text: "El Teresazo / El María Luisa", meaning: "El trago o golpe característico de ellas." },
    { id: 189, text: "Mamita delira acuérdate de mí", meaning: "Exageración." },
    { id: 190, text: "La bruja", meaning: "La esposa o la mamá (con cariño o respeto)." },
    { id: 191, text: "Me la fui agarrando y poniendo en su lugar", meaning: "Puse orden." },
    { id: 192, text: "Aconcharon los meaos", meaning: "Se asustaron." },
    { id: 193, text: "Súper Saya", meaning: "Súper Sayayin (fuerte)." },
    { id: 194, text: "Gangocho", meaning: "Tela de saco (o alguien mal vestido)." },
    { id: 195, text: "Chitecos", meaning: "Zapatos grandes o feos." },
    { id: 196, text: "No estaba la tonta", meaning: "Sarcasmo, sí estaba." },
    { id: 197, text: "Acábate mundito", meaning: "Ya no hay esperanza o pasó algo increíble." },
    { id: 198, text: "Recontramacanudo", meaning: "Súper bueno." },
    { id: 199, text: "Weón cocido", meaning: "Borracho." },
    { id: 200, text: "Los chingues", meaning: "El olor a zorrillo." },
    { id: 201, text: "La oreja parada", meaning: "Atento a todo." },
    { id: 202, text: "Nadando en aceite vienen", meaning: "Comida grasosa." },
    { id: 203, text: "Andái sorriando", meaning: "Andas coqueteando o sonriendo falsamente." }
];

window.appData = { phrases: phrases };
